# Generated by Django 2.1.7 on 2019-03-07 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('ref_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('emailAddress', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=100)),
                ('workgroup', models.CharField(max_length=10)),
                ('speciality', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('emailAddress', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.User'),
        ),
    ]
