# Generated by Django 2.1.7 on 2019-03-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190308_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='country',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='county',
        ),
    ]
